/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author KEVIN LANDIVAR
 */
public class Vis_Permisos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vis_Permisos
     */
    public Vis_Permisos() {
        initComponents();
    }

    public JTable getTablapermisos() {
        return tablapermisos;
    }

    public JButton getBtn_seleccionar() {
        return btn_seleccionar;
    }

    public void setBtn_seleccionar(JButton btn_seleccionar) {
        this.btn_seleccionar = btn_seleccionar;
    }

    public void setTablapermisos(JTable tablapermisos) {
        this.tablapermisos = tablapermisos;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JTextField getTxtidRol() {
        return txtidRol;
    }

    public void setTxtidRol(JTextField txtidRol) {
        this.txtidRol = txtidRol;
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btn_seleccionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablapermisos = new javax.swing.JTable();
        txtidRol = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel1.setText("PERMISOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 11, 256, 62));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/Save-icon (4).png"))); // NOI18N
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        btn_seleccionar.setText("SELECCIONAR TODO");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jScrollPane2.setViewportView(tablapermisos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 220));
        getContentPane().add(txtidRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_seleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablapermisos;
    private javax.swing.JTextField txtidRol;
    // End of variables declaration//GEN-END:variables
}
