/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author USUARIO
 */
public class Vis_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista_inicio
     */
    public Vis_Principal() {
        initComponents();

    }

   

    public JMenuItem getBtn_perfil() {
        return btn_perfil;
    }

    public void setBtn_perfil(JMenuItem btn_perfil) {
        this.btn_perfil = btn_perfil;
    }

    public JMenuItem getBtn_persona() {
        return btn_persona;
    }

    public void setBtn_persona(JMenuItem btn_persona) {
        this.btn_persona = btn_persona;
    }

    public JMenuItem getBtn_roles() {
        return btn_roles;
    }

    public void setBtn_roles(JMenuItem btn_roles) {
        this.btn_roles = btn_roles;
    }

    public JMenuItem getBtn_salir() {
        return btn_salir;
    }

    public void setBtn_salir(JMenuItem btn_salir) {
        this.btn_salir = btn_salir;
    }

    public JMenuItem getBtn_usuario() {
        return btn_usuario;
    }

    public void setBtn_usuario(JMenuItem btn_usuario) {
        this.btn_usuario = btn_usuario;
    }

     public JDesktopPane getESCRITORIO() {
        return ESCRITORIO;
    }

    public void setESCRITORIO(JDesktopPane ESCRITORIO) {
        this.ESCRITORIO = ESCRITORIO;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESCRITORIO = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_USUARIO = new javax.swing.JMenu();
        btn_usuario = new javax.swing.JMenuItem();
        btn_salir = new javax.swing.JMenuItem();
        MENU_ACADEMICO = new javax.swing.JMenu();
        btn_perfil = new javax.swing.JMenuItem();
        btn_persona = new javax.swing.JMenuItem();
        btn_roles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ESCRITORIOLayout = new javax.swing.GroupLayout(ESCRITORIO);
        ESCRITORIO.setLayout(ESCRITORIOLayout);
        ESCRITORIOLayout.setHorizontalGroup(
            ESCRITORIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        ESCRITORIOLayout.setVerticalGroup(
            ESCRITORIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        MENU_USUARIO.setText("USUARIO");

        btn_usuario.setText("Nuevo");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        MENU_USUARIO.add(btn_usuario);

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        MENU_USUARIO.add(btn_salir);

        jMenuBar1.add(MENU_USUARIO);

        MENU_ACADEMICO.setText("ACADEMICO");

        btn_perfil.setText("Perfil");
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        MENU_ACADEMICO.add(btn_perfil);

        btn_persona.setText("Persona");
        btn_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personaActionPerformed(evt);
            }
        });
        MENU_ACADEMICO.add(btn_persona);

        btn_roles.setText("Roles");
        btn_roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rolesActionPerformed(evt);
            }
        });
        MENU_ACADEMICO.add(btn_roles);

        jMenuBar1.add(MENU_ACADEMICO);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ESCRITORIO)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ESCRITORIO)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personaActionPerformed

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rolesActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_rolesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ESCRITORIO;
    private javax.swing.JMenu MENU_ACADEMICO;
    private javax.swing.JMenu MENU_USUARIO;
    private javax.swing.JMenuItem btn_perfil;
    private javax.swing.JMenuItem btn_persona;
    private javax.swing.JMenuItem btn_roles;
    private javax.swing.JMenuItem btn_salir;
    private javax.swing.JMenuItem btn_usuario;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
