/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class Vis_Materias extends javax.swing.JInternalFrame {
    private DefaultTableModel model;

    /**
     * Creates new form Vis_Materias
     */
    public Vis_Materias() {
        initComponents();
    }

    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }

    public JButton getBtnguardar() {
        return btnguardar;
    }

    public void setBtnguardar(JButton btnguardar) {
        this.btnguardar = btnguardar;
    }

    public JComboBox<String> getComboCarrera_mat() {
        return comboCarrera_mat;
    }

    public void setComboCarrera_mat(JComboBox<String> comboCarrera_mat) {
        this.comboCarrera_mat = comboCarrera_mat;
    }

    public JComboBox<String> getCombociclo() {
        return combociclo;
    }

    public void setCombociclo(JComboBox<String> combociclo) {
        this.combociclo = combociclo;
    }

    public JComboBox<String> getComboejeformacion() {
        return comboejeformacion;
    }

    public void setComboejeformacion(JComboBox<String> comboejeformacion) {
        this.comboejeformacion = comboejeformacion;
    }

    public JComboBox<String> getComboplan() {
        return comboplan;
    }

    public void setComboplan(JComboBox<String> comboplan) {
        this.comboplan = comboplan;
    }

    public JTable getTablamateria() {
        return tablamateria;
    }

    public void setTablamateria(JTable tablamateria) {
        this.tablamateria = tablamateria;
    }

    public JTextField getTxtcodmateria() {
        return txtcodmateria;
    }

    public void setTxtcodmateria(JTextField txtcodmateria) {
        this.txtcodmateria = txtcodmateria;
    }

    public JTextField getTxtcreditos() {
        return txtcreditos;
    }

    public void setTxtcreditos(JTextField txtcreditos) {
        this.txtcreditos = txtcreditos;
    }

    public JTextField getTxtnombremateria() {
        return txtareacarrera;
    }

    public void setTxtnombremateria(JTextField txtnombremateria) {
        this.txtareacarrera = txtnombremateria;
    }

    public JTextField getTxtareacarrera() {
        return txtareacarrera;
    }

    public void setTxtareacarrera(JTextField txtareacarrera) {
        this.txtareacarrera = txtareacarrera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodmateria = new javax.swing.JTextField();
        txtnombremateria1 = new javax.swing.JTextField();
        txtareacarrera = new javax.swing.JTextField();
        comboCarrera_mat = new javax.swing.JComboBox<>();
        comboejeformacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combociclo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtcreditos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboplan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamateria = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Ingreso de Materias");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Carrera*");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Eje de formaciòn*");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Còdigo de Materia*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nombre de la Materia*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 20));
        getContentPane().add(txtcodmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 150, -1));
        getContentPane().add(txtnombremateria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 130, -1));

        txtareacarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareacarreraActionPerformed(evt);
            }
        });
        getContentPane().add(txtareacarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 110, -1));

        comboCarrera_mat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Entrenamiento Deportivo", "Tecnología en Análisis de Sistemas", "Tecnología en Desarrollo Infantil Integral ", "Tecnología en Seguridad Penitenciaria ", "Tecnología Superior en Asesoría Financiera ", "Tecnología Superior en Desarrollo de Software ", "Tecnología Superior en Electricidad", "Tecnología Superior en Mecánica Industrial", "Tecnología Superior en Procesamiento Industrial de la Madera", "Técnico Superior en Seguridad Ciudadana y Orden Público ", "Tecnología Superior en Control de Incendios y Operaciones de Rescate", "Tecnología en Gestión del Patrimonio Histórico Cultural", "Tecnología Superior en Ciberseguridad", "Producción y Realización Audiovisual", "Tecnología Superior en Big Data", " " }));
        getContentPane().add(comboCarrera_mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, -1));

        comboejeformacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        getContentPane().add(comboejeformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ciclo*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 20));

        combociclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Sèptimo", "Octavo" }));
        combociclo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(combociclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Crèditos*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 20));
        getContentPane().add(txtcreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Plan de Clase*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Àrea de carrera*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, 20));

        comboplan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Uno", "Dos", "Tres", "Cuatro", "Cinco", "Seis", " ", " " }));
        getContentPane().add(comboplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 120, -1));

        tablamateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Carrera", "Eje de Formaciòn", "Còd Materia", "Nombre Materia", "Ciclo", "Crèditos", "Plan de clase", "Àrea de carrera"
            }
        ));
        jScrollPane1.setViewportView(tablamateria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 740, 230));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 10, 300));

        btnguardar.setText("Guardar");
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, 30));

        btncancelar.setText("Cancelar");
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtareacarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareacarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtareacarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> comboCarrera_mat;
    private javax.swing.JComboBox<String> combociclo;
    private javax.swing.JComboBox<String> comboejeformacion;
    private javax.swing.JComboBox<String> comboplan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tablamateria;
    private javax.swing.JTextField txtareacarrera;
    private javax.swing.JTextField txtcodmateria;
    private javax.swing.JTextField txtcreditos;
    private javax.swing.JTextField txtnombremateria1;
    // End of variables declaration//GEN-END:variables
}
