/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POA.Vista;

/**
 *
 * @author MIGUEL
 */
public class vis_Persona extends javax.swing.JInternalFrame {

    /**
     * Creates new form vis_Persona
     */
    public vis_Persona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbFoto = new javax.swing.JLabel();
        btnCargarFoto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 56, 107));
        jLabel3.setText("Persona");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(235, 192, 36));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/guardar.png"))); // NOI18N
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 50, 30));

        btnModificar.setBackground(new java.awt.Color(235, 192, 36));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/modificar.png"))); // NOI18N
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        panel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 40, 30));

        btnNuevo.setBackground(new java.awt.Color(235, 192, 36));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/nuevo.png"))); // NOI18N
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        panel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 50, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/image (1).jpg"))); // NOI18N
        panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, 120));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/impresion.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 40, 30));

        jLabel15.setText("Guardar");
        panel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jLabel16.setText("Modificar");
        panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel17.setText("Nuevo");
        panel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel18.setText("Imprimir");
        panel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 120));

        panel2.setBackground(new java.awt.Color(6, 56, 107));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 55, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Formulario");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cedula:");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombres:");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellidos:");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Nacimiento:");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo:");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Direccion:");
        panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Celular:");
        panel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Foto");
        panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtCedula.setBorder(null);
        txtCedula.setOpaque(false);
        panel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 170, 20));

        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        panel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 170, 20));

        txtApellido.setBorder(null);
        txtApellido.setOpaque(false);
        panel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 170, 20));

        txtCorreo.setBorder(null);
        txtCorreo.setOpaque(false);
        panel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 20));

        txtDireccion.setBorder(null);
        txtDireccion.setOpaque(false);
        panel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 170, 20));

        txtCelular.setBorder(null);
        txtCelular.setOpaque(false);
        panel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 170, 20));
        panel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 170, -1));

        lbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/imagen.png"))); // NOI18N
        panel2.add(lbFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, 130));

        btnCargarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/cargar foto.png"))); // NOI18N
        btnCargarFoto.setBorderPainted(false);
        btnCargarFoto.setContentAreaFilled(false);
        panel2.add(btnCargarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 40, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 170, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 170, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 170, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 170, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        panel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/logo blanco (1).png"))); // NOI18N
        panel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 350, 590));

        panel3.setBackground(new java.awt.Color(37, 63, 90));
        panel3.setEnabled(false);
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePersonas);

        panel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 208, 703, 360));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista Persona");
        panel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/POA/Vista/img/buscar (2).png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        panel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 40, -1));

        txtBuscar.setBorder(null);
        txtBuscar.setOpaque(false);
        panel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 220, 20));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        panel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 220, 10));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 760, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarFoto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbFoto;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTable tablePersonas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
