package POA.Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Isaac Mejia
 */
public class vis_PeriodoAcademico extends javax.swing.JInternalFrame {

    /**
     * Creates new form vis_PeriodoAcademico
     */
    public vis_PeriodoAcademico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        lblIdPeriodo = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        mesPeriodoInicio = new com.toedter.calendar.JMonthChooser();
        anioPeriodoInicio = new com.toedter.calendar.JYearChooser();
        mesPeriodoFin = new com.toedter.calendar.JMonthChooser();
        anioPeriodoFin = new com.toedter.calendar.JYearChooser();
        lblNombrePeriodo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID PERIODO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblCarrera.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 150, 20));

        jLabel3.setText("Carrera:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel4.setText("FechaInicio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel5.setText("FechaFin:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel6.setText("Estado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABIERTO", "CERRADO" }));
        jPanel1.add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, -1));

        lblIdPeriodo.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(lblIdPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 20));

        btnCrear.setText("CREAR");
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        jPanel1.add(mesPeriodoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));
        jPanel1.add(anioPeriodoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));
        jPanel1.add(mesPeriodoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jPanel1.add(anioPeriodoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        lblNombrePeriodo.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(lblNombrePeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anioPeriodoFin;
    private com.toedter.calendar.JYearChooser anioPeriodoInicio;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblIdPeriodo;
    private javax.swing.JLabel lblNombrePeriodo;
    private com.toedter.calendar.JMonthChooser mesPeriodoFin;
    private com.toedter.calendar.JMonthChooser mesPeriodoInicio;
    // End of variables declaration//GEN-END:variables
}
